#!/bin/sh

search_dir=/home/major/Pictures/WallpapersLock/

declare -a files

for entry in "$search_dir"*
do
	if [[ $entry == *"png" ]];
		then
		files+=($entry)
	fi
done

len=${#files[@]}

random=$(($RANDOM%len))

set -e
xset s off dpms 0 10 0

#i3lock -i ${files[$random]} --ignore-empty-password --nofork --insidecolor=373445ff --ringcolor=ffffffff --line-uses-inside     --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000     --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff     --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+86:y+700"     --radius=15 --veriftext="" --wrongtext=""

#i3lock -p win -t -i ${files[$random]} --ignore-empty-password --nofork --insidecolor=373445ff --ringcolor=ffffffff --line-uses-inside     --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000     --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff     --ringvercolor=ffffffff --ringwrongcolor=ffffffff     --radius=15 --veriftext="" --wrongtext=""

i3lock -p win -t --blur 5 --ignore-empty-password --nofork --insidecolor=373445ff --ringcolor=ffffffff --line-uses-inside     --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000     --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff     --ringvercolor=ffffffff --ringwrongcolor=ffffffff     --radius=15 --veriftext="" --wrongtext=""

xset s off -dpms

