#!/bin/sh

#!/bin/sh

declare -i updates_aur updates_arch updates

if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
    updates_arch=0
fi

if ! updates_aur=$(checkupdates-aur 2> /dev/null | wc -l ); then
    updates_aur=0
fi

updates=${updates_arch}+${updates_aur}
color='#f72f34'

if [ "$updates_arch" -gt 0 ] && [ "$updates_aur" -gt 0 ]; then
    echo "%{F$color}%{F-} $updates_arch %{F$color}%{F-} $updates_aur"
elif [ "$updates_arch" -gt 0 ]; then
	echo " $updates_arch"
elif [ "$updates_aur" -gt 0 ]; then
	echo " $updates_aur"
else
    echo ""
fi
