#!/bin/bash

declare -c title
declare -c artist

player_status=$(playerctl status 2> /dev/null)
if [[ $? -eq 0 ]]; then
	artist="$(playerctl metadata artist)"
	lenny=${#artist}
	if [[ $lenny -gt 9 ]]; then
		artist="${artist:0:9}..."
	else
		artist=${artist:0:9}
	fi

	title="$(playerctl metadata title)"
	# title="${title,,}"
	# title=${title^^${title:0:1}}
	lenny=${#title}
	if [[ $lenny -gt 19 ]]; then
		title="${title:0:20}..."
	else
		title=${title:0:20}
	fi
	metadata="${artist} - ${title}"
fi

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
    echo "%{F#FFFFFF}$metadata%{F-}"
elif [[ $player_status = "Paused" ]]; then
    echo "%{F#330000}$metadata%{F-}"
else
    echo ""
fi
