#!/bin/bash

player_status=$(playerctl status 2> /dev/null)
if [[ $? -eq 0 ]]; then
	artist="$(playerctl metadata artist)"
	artist=${artist:0:9}
	title="$(playerctl metadata title)"
	title=${title:0:20}
	metadata="${artist} - ${title}"
fi

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
    echo "%{F#00FF00}$metadata%{F-}"
elif [[ $player_status = "Paused" ]]; then
    echo "%{F#FF0000}$metadata%{F-}"
else
    echo ""
fi
